services:
  - type: web
    name: elevateu-backend
    runtime: python
    pythonVersion: 3.11
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn elevateu_backend.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: elevateu-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: https://yourdomain.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://yourvercelapp.vercel.app

databases:
  - name: elevateu-db
    plan: free
    databaseName: elevateu
